#!/usr/bin/env bash
#
# Generates the open-class lexicon, src/tag/lexicon.txt, from the sources lexicon.lock pins, and
# copies their notices into LICENSES/. Run by hand: nothing in the build, the tests or CI calls it,
# and the build never reads .lexicon, where the downloads and the working files go.
#
#   generate.sh generate [SIZE]   fetch and verify the sources, then write the lexicon at SCOWL size
#                                 level SIZE, the lock's `size` when it is left out
#   generate.sh fetch             only fetch and verify the sources
#
# The lexicon is the words SCOWL has at SIZE or below, each with the readings WordNet, Moby and
# AGID give it, ranked by what merge.awk says. See the header of that file for the rules, and the
# header the lexicon opens with for what it was built from. The same sources and size always give
# the same bytes.
#
# .lexicon/dl holds the downloads, kept between runs: one whose sha256 is the lock's is not fetched
# again, and one that differs is replaced. .lexicon/work holds what a run extracts and normalises,
# and is cleared at the start of the next. A download that fails its checksum stops the run, and
# nothing in the tree is written until every file has passed.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
LOCK="$HERE/lexicon.lock"
CACHE="$ROOT/.lexicon"
DL="$CACHE/dl"
WORK="$CACHE/work"
OUT="$ROOT/src/tag/lexicon.txt"
NOTICES="$ROOT/LICENSES"
SELF="${HERE#"$ROOT/"}/$(basename "${BASH_SOURCE[0]}")"
LOCK_REL="${HERE#"$ROOT/"}/lexicon.lock"

# The scripts and sort are told to compare bytes, so the lexicon does not depend on the locale.
export LC_ALL=C

fail() {
    cat >&2 <<MSG

Error in:
$SELF

The open-class lexicon is generated by hand from the sources pinned in $LOCK_REL. Nothing in the
build needs this script. A failure has occurred in it.

Error message:
$*
MSG
    exit 1
}

# The sha256 of a file, with the tool this machine has.
sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d ' ' -f 1
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | cut -d ' ' -f 1
    else
        fail "Neither sha256sum nor shasum is installed, and one of them checks the downloads."
    fi
}

# The value of a one-line key of the lock.
lock_value() {
    local value
    value="$(awk -v key="$1" '$1 == key { sub(/^[^ ]+ +/, ""); print; exit }' "$LOCK")"
    [ -n "$value" ] || fail "$LOCK_REL has no line for $1."
    printf '%s\n' "$value"
}

# Downloads each file the lock names that is not in the cache with its sha256, and checks it.
fetch() {
    [ -f "$LOCK" ] || fail "$LOCK_REL is missing."
    command -v curl >/dev/null 2>&1 || fail "curl is not installed, and it downloads the sources."
    mkdir -p "$DL"
    local name sum url got
    while read -r _ name sum url; do
        if [ -f "$DL/$name" ] && [ "$(sha256_of "$DL/$name")" = "$sum" ]; then
            continue
        fi
        echo "lexicon: fetching $name"
        curl --fail --silent --show-error --location --retry 3 --output "$DL/$name.part" "$url" \
            || fail "Could not download $url"
        got="$(sha256_of "$DL/$name.part")"
        if [ "$got" != "$sum" ]; then
            rm -f "$DL/$name.part"
            fail "$name has sha256 $got, and $LOCK_REL pins $sum."
        fi
        mv "$DL/$name.part" "$DL/$name"
    done < <(awk '$1 == "file"' "$LOCK")
}

# Unpacks the archives into the work directory and normalises each source to tab separated records,
# the form merge.awk reads.
normalise() {
    local size="$1"
    rm -rf "$WORK"
    mkdir -p "$WORK/scowl" "$WORK/agid" "$WORK/wordnet"
    tar -xzf "$DL/scowl-2020.12.07.tar.gz" -C "$WORK/scowl" --strip-components 1
    tar -xzf "$DL/agid-2016.01.19.tar.gz" -C "$WORK/agid" --strip-components 1
    tar -xzf "$DL/WNdb-3.0.tar.gz" -C "$WORK/wordnet"

    # SCOWL: form, size level, and `u` for a list of capitalised words or `w` for the plain lists.
    # Every dialect's lists count. A form is lower case, letters and apostrophes only, with no
    # possessive `'s` (the tagger reads that from the stem), no leading or trailing apostrophe, and
    # no more than 24 bytes, which is what the loader folds. The tokenizer never makes a word of a
    # hyphenated entry, so those go too.
    local list
    for list in english american british canadian australian; do
        for f in "$WORK/scowl/final/$list"-words.* "$WORK/scowl/final/$list"-upper.* \
            "$WORK/scowl/final/$list"-proper-names.*; do
            [ -e "$f" ] || continue
            printf '%s\n' "$f"
        done
    done | xargs awk -v size="$size" '
        BEGIN { OFS = "\t" }
        FNR == 1 {
            level = FILENAME
            sub(/^.*\./, "", level)
            kind = (FILENAME ~ /-words\./) ? "w" : "u"
        }
        level + 0 <= size + 0 {
            w = tolower($0)
            if (w !~ /^[a-z]([a-z'"'"']*[a-z])?$/) next
            if (w ~ /'"'"'s$/ || length(w) > 24) next
            print w, level, kind
        }' | sort -u >"$WORK/scowl.tsv"

    # WordNet: each single word lemma with its part of speech, tag count and sense count, and the
    # names among the nouns. The tag count is the sum, over the lemma's senses, of the count in
    # index.sense of how often the sense was met in SemCor, the sense-tagged corpus; a lemma's
    # `tagsense_cnt` in the index files only counts the senses that were met at least once, which
    # says little of how often the lemma is used as that part of speech. The index files lower-case every lemma, so a name such as
    # `paris` looks like a common noun there; the data files keep the case. A noun lemma is a common
    # noun when some synset spells it in lower case, and a name when only capitalised forms are
    # there, or one is in a synset with an instance hypernym. An index line is: lemma pos synset_cnt p_cnt
    # ptr_symbol... sense_cnt tagsense_cnt offset...; a data line is: offset lex_filenum ss_type
    # w_cnt (hex) word lex_id... p_cnt (symbol offset pos source/target)...
    local dict="$WORK/wordnet/dict" pair
    awk '
        BEGIN {
            OFS = "\t"
            for (i = 0; i < 16; i++) hex[substr("0123456789abcdef", i + 1, 1)] = i
        }
        $1 !~ /^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$/ { next }
        {
            n = hex[substr($4, 1, 1)] * 16 + hex[substr($4, 2, 1)]
            p = $(5 + 2 * n) + 0
            instance = 0
            for (j = 0; j < p; j++) if ($(6 + 2 * n + 4 * j) == "@i") instance = 1
            for (j = 0; j < n; j++) {
                w = $(5 + 2 * j)
                if (w !~ /^[A-Za-z]([A-Za-z'"'"']*[A-Za-z])?$/) continue
                if (w !~ /^[A-Z]/) print tolower(w), "C"
                else if (instance) print tolower(w), "I"
                else print tolower(w), "U"
            }
        }
    ' "$dict/data.noun" | sort -u | awk '
        BEGIN { FS = OFS = "\t" }
        { kinds[$1] = kinds[$1] $2 }
        END {
            for (w in kinds) {
                k = kinds[w]
                if (k ~ /C/) print w, "C"
                if (k ~ /I/ || k !~ /C/) print w, "P"
            }
        }
    ' | sort >"$WORK/nouns.tsv"
    # The offsets of the noun synsets that are instances: a name's senses are not the common noun's.
    awk '
        BEGIN { for (i = 0; i < 16; i++) hex[substr("0123456789abcdef", i + 1, 1)] = i }
        $1 !~ /^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$/ { next }
        {
            n = hex[substr($4, 1, 1)] * 16 + hex[substr($4, 2, 1)]
            p = $(5 + 2 * n) + 0
            for (j = 0; j < p; j++) if ($(6 + 2 * n + 4 * j) == "@i") { print $1; break }
        }
    ' "$dict/data.noun" | sort -u >"$WORK/instances.txt"
    # SemCor counts: a sense key is lemma%ss_type:..., with ss_type 1 noun, 2 verb, 3 adjective, 4
    # adverb and 5 adjective satellite; the line goes on with the synset offset, the sense number
    # and the count. Each lemma's counts add up per part of speech, a noun's without its instances.
    awk -v instances="$WORK/instances.txt" '
        BEGIN {
            OFS = "\t"
            while ((getline line < instances) > 0) instance[line] = 1
        }
        {
            split($1, key, "%")
            lemma = key[1]
            split(key[2], part, ":")
            type = part[1] + 0
            pos = (type == 1) ? "n" : (type == 2) ? "v" : (type == 3 || type == 5) ? "a" : (type == 4) ? "r" : ""
            if (pos == "" || lemma !~ /^[a-z]([a-z'"'"']*[a-z])?$/) next
            if (pos == "n" && ($2 in instance)) next
            count[lemma SUBSEP pos] += $4
        }
        END {
            for (k in count) {
                split(k, f, SUBSEP)
                print f[1], f[2], count[k]
            }
        }
    ' "$dict/index.sense" | sort >"$WORK/counts.tsv"
    for pair in noun:n verb:v adj:a adv:r; do
        awk -v pos="${pair#*:}" -v nouns="$WORK/nouns.tsv" -v counts="$WORK/counts.tsv" '
            BEGIN {
                OFS = "\t"
                while ((getline line < nouns) > 0) {
                    split(line, f, "\t")
                    kind[f[1] SUBSEP f[2]] = 1
                }
                while ((getline line < counts) > 0) {
                    split(line, f, "\t")
                    count[f[1] SUBSEP f[2]] = f[3]
                }
            }
            /^ / { next }
            $1 !~ /^[a-z]([a-z'"'"']*[a-z])?$/ { next }
            pos == "n" && !(($1 SUBSEP "C") in kind) { next }
            { print $1, pos, (($1 SUBSEP pos) in count) ? count[$1 SUBSEP pos] : 0, $3 }
        ' "$dict/index.${pair%:*}"
    done >"$WORK/wordnet.tsv"
    awk -F '\t' 'BEGIN { OFS = "\t" } $2 == "P" { print $1, "P", 0, 0 }' "$WORK/nouns.tsv" >>"$WORK/wordnet.tsv"

    # Moby: word, tag letters, and 1 when the entry is capitalised. One word entries of letters and
    # apostrophes only; the file has CRLF line ends and the backslash as its separator.
    tr -d '\r' <"$DL/mobypos.txt" | awk -F '\\' '
        BEGIN { OFS = "\t" }
        $1 ~ /^[A-Za-z]([A-Za-z'"'"']*[A-Za-z])?$/ && $2 != "" {
            print tolower($1), $2, ($1 ~ /^[A-Z]/) ? 1 : 0
        }
    ' >"$WORK/moby.tsv"

    # AGID: form, lemma, part of speech and slot, for each lemma entry whose part of speech its
    # database knows (no `?` after it), each form it gives without a mark that says it is doubtful
    # (`!`, `?`, `~`) and with a variant level below 2, and is not the lemma itself. Nouns give a plural; adjectives and adverbs
    # share an entry that gives the comparative and the superlative; verbs give the past tense, the
    # past participle if it differs, the -ing form and the -s form. The two verbs whose entries have
    # more forms than that, `be` and `wit`, are left out.
    awk '
        BEGIN { OFS = "\t" }
        $1 !~ /^[a-z]([a-z'"'"']*[a-z])?$/ { next }
        $2 != "N:" && $2 != "V:" && $2 != "A:" { next }
        {
            lemma = $1
            pos = substr($2, 1, 1)
            rest = $0
            sub(/^[^:]*: /, "", rest)
            ngroups = split(rest, group, / \| /)
            if (pos == "N") { slots = "pl"; want = 1 }
            else if (pos == "A") { slots = "cmp sup"; want = 2 }
            else if (ngroups == 3) { slots = "pastpp ing s"; want = 3 }
            else if (ngroups == 4) { slots = "past pp ing s"; want = 4 }
            else next
            if (ngroups != want) next
            split(slots, slot, " ")
            for (g = 1; g <= ngroups; g++) {
                nentries = split(group[g], entry, /, /)
                for (e = 1; e <= nentries; e++) {
                    nfields = split(entry[e], field, " ")
                    form = field[1]
                    marks = form
                    gsub(/[a-z'"'"']/, "", marks)
                    sub(/[<~!?]+$/, "", form)
                    if (marks ~ /[!?~]/) continue
                    if (nfields > 1 && field[2] ~ /^[0-9.]+$/ && field[2] + 0 >= 2) continue
                    if (form !~ /^[a-z]([a-z'"'"']*[a-z])?$/ || length(form) > 24) continue
                    if (form == lemma) continue
                    print form, lemma, pos, slot[g]
                }
            }
        }
    ' "$WORK/agid/infl.txt" | sort -u >"$WORK/agid.tsv"
}

# Copies the notice of each source from its download into LICENSES/, unchanged.
notices() {
    mkdir -p "$NOTICES"
    cp "$WORK/scowl/Copyright" "$NOTICES/SCOWL.txt"
    # The AGID readme's last part, from its copyright notice to the end.
    awk '/^COPYRIGHT AND SOURCE:/ { on = 1 } on' "$WORK/agid/README" >"$NOTICES/AGID.txt"
    # The licence at the head of every WordNet data file, its first 29 lines, less the line numbers
    # that the file's format puts before each.
    head -n 29 "$WORK/wordnet/dict/data.noun" | sed -E 's/^ +[0-9]+ ?//' >"$NOTICES/WordNet.txt"
    cp "$DL/moby-readme.txt" "$NOTICES/Moby.txt"
    [ -s "$NOTICES/AGID.txt" ] || fail "The AGID readme has no copyright notice to copy."
}

generate() {
    local size="${1:-$(lock_value size)}"
    case "$size" in
        10 | 20 | 35 | 40 | 50 | 55 | 60 | 70 | 80 | 95) ;;
        *) fail "SIZE is $size; SCOWL's size levels are 10, 20, 35, 40, 50, 55, 60, 70, 80 and 95." ;;
    esac
    fetch
    normalise "$size"
    local body="$WORK/lexicon.body"
    awk -v size="$size" -f "$HERE/merge.awk" \
        "$WORK/scowl.tsv" "$WORK/wordnet.tsv" "$WORK/moby.tsv" "$WORK/agid.tsv" | sort >"$body"
    [ -s "$body" ] || fail "The merge wrote no word."

    {
        echo "# The open-class lexicon: a word, a tab, then its readings. Generated by"
        echo "# scripts/lexicon/generate.sh from the sources scripts/lexicon/lexicon.lock pins; do not"
        echo "# edit it. The notice of each source is in LICENSES/. Sorted bytewise, one word a line."
        echo "#"
        echo "# size $size"
        echo "# words $(wc -l <"$body" | tr -d ' ')"
        while read -r _ name sum _; do
            echo "# source $name sha256 $sum"
        done < <(awk '$1 == "file"' "$LOCK")
        echo "#"
        echo "# The readings are tag letters, best guess first, and after the first an uppercase letter"
        echo "# for its features. Tags: n noun, p proper noun, v verb, a adjective, r adverb,"
        echo "# q pronoun, d determiner, i adposition, c conjunction, j interjection. Features: S singular,"
        echo "# P plural, I infinitive, D finite past, E past participle, G present participle, Z third"
        echo "# person singular present, O positive, C comparative, T superlative."
        cat "$body"
    } >"$OUT.new"
    mv "$OUT.new" "$OUT"
    notices
    echo "lexicon: $(wc -l <"$body" | tr -d ' ') words, $(wc -c <"$OUT" | tr -d ' ') bytes, in ${OUT#"$ROOT/"}"
}

case "${1:?usage: generate.sh generate [SIZE] | generate.sh fetch}" in
    generate) generate "${2:-}" ;;
    fetch) fetch ;;
    *) fail "Unknown command '$1'. The usage is: generate.sh generate [SIZE] | generate.sh fetch" ;;
esac
